CC=gcc
CFLAGS= -Wall
CFLAGS+= -g
CFLAGS+= -m32
CFLAGS+= -Werror
#CFLAGS+= -pedantic
CFLAGS+= -I/home/mahieddine/Documents/cours/M1S1/ASE/libs/include
CFLAGS+= -L/home/mahieddine/Documents/cours/M1S1/ASE/libs/lib -lhardware
RM= rm -rf

TRASH= *# *~ *.o

FILE=





all: contexte

clean:
	$(RM) *# *~ *.o
realclean:
	$(RM) $(TRASH) $(FILE)
